version: '3.8'
services:
  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./server:/app

  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 5
      net.ipv4.ip_local_port_range: "32768 32774"
    volumes:
      - ./client:/app
    depends_on:
      - server1
      - server2